name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_win:
    name: Building Windows binaries
    runs-on: windows-latest
    needs: [build_linux]
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --release
    - uses: actions/upload-artifact@v2
      with:
        path: target/release/*.exe
      
  build_linux:
    name: Building Linux binaries
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --release && strip target/release/CandorStart && mv target/release/CandorStart target/release/CandorStart_linux
    - uses: actions/upload-artifact@v2
      with:
        path: target/release/CandorStart_linux
  
  build_mac:
    name: Building Mac binaries
    runs-on: macos-latest
    needs: [build_linux]
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --release && strip target/release/CandorStart && mv target/release/CandorStart target/release/CandorStart_mac
    - uses: actions/upload-artifact@v2
      with:
        path: target/release/CandorStart_mac
