name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_win:
    name: Building Windows binaries
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - uses: actions/upload-artifact@v2
      with:
        path: "*/*.exe"
      
  build_linux:
    name: Building Linux binaries
    runs-on: ubuntu-latest
    needs: [build_win]
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - uses: actions/upload-artifact@v2
      with:
        path: "*/*.exe"
  
  build_mac:
    name: Building Mac binaries
    runs-on: macos-latest
    needs: [build_linux]
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - uses: actions/upload-artifact@v2
      with:
        path: "*/*.exe"
